baseURL: "https://hellwing.github.io/"
module:
  vendor: true
languageCode: "en-us"
title: "Wojciech Hellwing"
theme: "wowchemy-starter-academic"
pagination:
  pagerSize: 10
outputs:
  home:
    - HTML
    - RSS
