name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          rm -rf $GITHUB_WORKSPACE/*
          rm -rf $GITHUB_WORKSPACE/.*
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          clean: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.137.1'
          extended: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Ensure Hugo Modules
        run: |
          hugo mod tidy
          hugo mod get -u
      - name: Build with Hugo
        run: hugo --minify --logLevel info
      - name: Copy homepage to root
        run: |
          if [ -f public/home/index.html ]; then
            cp public/home/index.html public/index.html
          fi
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
